messages:
  # Add %prefix% for prefix, yeah
  # Add %player% for player name
  # Add %time% for time in HH:MM:SS
  # Add %date% for date in MM:DD
  # Add %year% for year
  # Add %mc_day% for minecraft day
  # See https://webui.advntr.dev/ for text formating
  prefix: "<aqua><b>[ItemSignment]</b></aqua>"
  no-item: "%prefix% <dark_red>You need to hold an item in your main hand!</dark_red>"
  no-sign: "%prefix% <dark_red>This item isn't signed!</dark_red>"
  not-author: "%prefix% <dark_red>You're not this sign author!</dark_red>"
  already-signed: "%prefix% <dark_red>This item is already signed!</dark_red>"
  sign-success: "%prefix% <green>Successfully signed the item.</green>"
  unsign-success: "%prefix% <green>Successfully unsigned the item.</green>"
  sign_all-success: "%prefix% <green>Successfully signed every item in the inventory.</green>"
  unsign_all-success: "%prefix% <green>Successfully unsigned every item in the inventory.</green>"
  sign: "<gradient:#AA00FF:#55FFFF>Signed by %player%</gradient>"
  error: "%prefix% <dark_red>Error. Contact the server owner.</dark_red>"
  error-console: "Error. Contact the plugin developer."

use-permissions: false # enable in case you need it
# permissions:
# itemsignment.sign.use
# itemsignment.sign_all.use
# itemsignment.unsign.use
# itemsignment.unsign_all.use